/// Auto-generated version info.
/// Generated by scripts/update_version.dart — DO NOT EDIT MANUALLY
class AppVersion {
  static const String name = '爪札';
  static const String version = '1.0.81';
  static const int build = 4081;
  static const String buildType = 'release';

  static String get full => 'v$version';
  static String get display => 'v$version';
  static String get subtitle => '$version ($buildType)';
}
