/// Update lib/core/utils/version.dart from pubspec.yaml
///
/// Run: dart scripts/update_version.dart [buildType]   (buildType: debug|release)
/// Called by scripts/build.bat before each build so the App "Me" tab
/// version follows pubspec; DO NOT hand-edit version.dart.
library;

import 'dart:io';

void main(List<String> args) {
  final pubspec = File('pubspec.yaml').readAsStringSync();
  final versionLine = pubspec
      .split('\n')
      .firstWhere((l) => l.startsWith('version:'));
  final versionStr = versionLine.split(':').last.trim();

  // Parse "1.0.0+2" -> version "1.0.0", build 2
  final parts = versionStr.split('+');
  final version = parts[0];
  final build = int.tryParse(parts.length > 1 ? parts[1] : '1') ?? 1;

  // Also get build type (explicit arg wins; default = debug)
  final buildType = args.isNotEmpty
      ? args[0]
      : (Platform.script.path.contains('release') ? 'release' : 'debug');

  final content =
      '''
/// Auto-generated version info.
/// Generated by scripts/update_version.dart — DO NOT EDIT MANUALLY
class AppVersion {
  static const String name = '爪札';
  static const String version = '$version';
  static const int build = $build;
  static const String buildType = '$buildType';

  static String get full => 'v\$version';
  static String get display => 'v\$version';
  static String get subtitle => '\$version (\$buildType)';
}
''';

  File('lib/core/utils/version.dart').writeAsStringSync(content);
  stdout.writeln('Updated version.dart: $versionStr ($buildType)');
}
